const translations = {
  tr: {
    title: "Renk Seçici",
    minimize: "Küçült",
    maximize: "Büyült",
    pick_color: "Renk Seç",
    color_preview: "Seçilen renk önizlemesi",
    current_hex: "Geçerli HEX renk kodu",
    formats_title: "Renk Formatları",
    hex_label: "HEX",
    rgb_label: "RGB",
    hsl_label: "HSL",
    cmyk_label: "CMYK",
    hwb_label: "HWB",
    lab_label: "LAB",
    xyz_label: "XYZ",
    copy_hex: "HEX kodunu kopyala",
    copy_rgb: "RGB kodunu kopyala",
    copy_hsl: "HSL kodunu kopyala",
    copy_cmyk: "CMYK kodunu kopyala",
    copy_hwb: "HWB kodunu kopyala",
    copy_lab: "LAB kodunu kopyala",
    copy_xyz: "XYZ kodunu kopyala",
    copied: "Kopyalandı!",
    pick_error: "Renk seçiminde hata oluştu",
    eyedropper_error: "EyeDropper API desteklenmiyor. Chrome 95+ kullanın.",
    history_color: "Geçmiş renk",
    language_label: "Dil",
    language_tr: "Türkçe",
    language_en: "İngilizce"
  },
  en: {
    title: "Color Picker",
    minimize: "Minimize",
    maximize: "Maximize",
    pick_color: "Pick Color",
    color_preview: "Selected color preview",
    current_hex: "Current HEX color code",
    formats_title: "Color Formats",
    hex_label: "HEX",
    rgb_label: "RGB",
    hsl_label: "HSL",
    cmyk_label: "CMYK",
    hwb_label: "HWB",
    lab_label: "LAB",
    xyz_label: "XYZ",
    copy_hex: "Copy HEX code",
    copy_rgb: "Copy RGB code",
    copy_hsl: "Copy HSL code",
    copy_cmyk: "Copy CMYK code",
    copy_hwb: "Copy HWB code",
    copy_lab: "Copy LAB code",
    copy_xyz: "Copy XYZ code",
    copied: "Copied!",
    pick_error: "Error picking color",
    eyedropper_error: "EyeDropper API not supported. Use Chrome 95+.",
    history_color: "History color",
    language_label: "Language",
    language_tr: "Turkish",
    language_en: "English"
  }
};